Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,8 +9,13 @@ jobs:
     steps:
       - name: Trigger another workflow
         run: |
-          curl -X POST \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
-            https://api.github.com/repos/ShmilyStar/OpenWrt-Actions-Compile/actions/workflows/编译固件.yml/dispatches \
-            -d '{"ref":"main"}'
+          response=$(curl -s -o response.json -w "%{http_code}" -X POST \
+          -H "Accept: application/vnd.github.v3+json" \
+          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
+          https://api.github.com/repos/ShmilyStar/OpenWrt-Actions-Compile/actions/workflows/编译固件.yml/dispatches \
+          -d '{"ref":"main"}')
+         
+          if [ "$response" -ne 201 ]; then
+            echo "Error triggering workflow: $(cat response.json)"
+            exit 1
+          fi
